# Composicao do programa de teste de uma lista genérica duplamente encadeada
# Este exemplo utiliza o arcabouço completo 

[Diretorios]

Nome        =  TesteListaDebug
PathDefault =  ..\Fontes
err         =  ..\Produto
lib         =  ..\Objetos
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes

[Modulos]
LISTA 		/D_DEBUG
TEST_LIS 	/D_DEBUG

[BuildInicio]
/OUT:..\Produto\TesteListaDebug.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
